build.gradle

PCQ_588
Removed IDAM client dependency.
```
[ ] Yes
[ X] No
```

PCQ_588_Removed IDAM dependenccy

---

build.gradle
charts/pcq-loader/Chart.yaml
charts/pcq-loader/requirements.yaml

PCQ_588
Fixed Spring Boot error
```
[ ] Yes
[ X] No
```

PCQ_588_Fixed Spring Boot Error

---

src/main/java/uk/gov/hmcts/reform/pcqloader/PcqLoaderApplication.java

PCQ_588
Cosmetic change to trigger a AAT build
```
[ ] Yes
[X ] No
```

PCQ_588_Cosmetic change to trigger build

---

infrastructure/storage-account-staging.tf
infrastructure/storage-account.tf
infrastructure/variables.tf

Blob storage creation script test.
```
[ ] Yes
[x] No
```

Pcq 588 blob storage configuration

---

infrastructure/storage-account.tf
infrastructure/variables.tf

Update to add missing infrastructure variables.
```
[ ] Yes
[x] No
```

PCQ-588: Updated to add missing variables.

---

infrastructure/storage-account.tf

Update to container configuration
```
[ ] Yes
[x] No
```

Pcq 588 blob storage container

---

infrastructure/storage-account.tf

Update container reference to module storage account name.
```
[ ] Yes
[x] No
```

PCQ-588: Correction to container config.

---

infrastructure/storage-account.tf

Update to revert back to a working build where just the storage account is created. Container added through UI until permissions can be corrected.
```
[ ] Yes
[x] No
```

PCQ-588 Remove container creation as this was done through UI.

---

infrastructure/outputs.tf
infrastructure/state.tf
infrastructure/storage-account.tf
infrastructure/variables.tf

**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
Fixing build.
```
[ ] Yes
[x] No
```

PCQ-588 fixing build.

---

.travis.yml
Dockerfile
src/main/java/uk/gov/hmcts/reform/pcqloader/PcqLoaderApplication.java
src/main/java/uk/gov/hmcts/reform/pcqloader/PcqLoaderComponent.java
src/main/java/uk/gov/hmcts/reform/pcqloader/utils/PcqLoaderUtils.java
src/test/java/uk/gov/hmcts/reform/pcqloader/PcqLoaderApplicationTest.java
src/test/java/uk/gov/hmcts/reform/pcqloader/PcqLoaderComponentTest.java
src/test/java/uk/gov/hmcts/reform/pcqloader/utils/PcqLoaderUtilsTest.java

PCQ-577
Updated docker file and travis file to explicitly specify openjdk11.
```
[ ] Yes
[X] No
```

PCQ-577_DCN_Number_Extraction

---

.gitignore
infrastructure/storage-account.tf

https://tools.hmcts.net/jira/browse/PCQ-572
Update to fix permissions with PCQ container.
```
[ ] Yes
[x] No
```

PCQ-572: Update to add pcq container.

---

infrastructure/providers.tf
infrastructure/storage-account.tf
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/PCQ-572
Add missing permissions.
```
[ ] Yes
[x] No
```

Pcq 572 blob storage authentication

---

infrastructure/aat.tfvars
infrastructure/storage-account.tf

https://tools.hmcts.net/jira/browse/PCQ-653
Update to add more permissions.
```
[ ] Yes
[x] No
```

PCQ-653: Updated rules for AKS access.

---

infrastructure/providers.tf
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/PCQ-653
Update to add subnet rules.
```
[ ] Yes
[x] No
```

Pcq 653 add blob storage aks access for bulk scan

---

infrastructure/aat.tfvars
infrastructure/demo.tfvars
infrastructure/providers.tf
infrastructure/storage-account.tf
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/PCQ-653
Update to add preview subnet rules.
```
[ ] Yes
[x] No
```

PCQ-653: Updated rules to add preview.

---

infrastructure/aat.tfvars
infrastructure/demo.tfvars
infrastructure/providers.tf
infrastructure/storage-account.tf
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/PCQ-653
Update demo with changes in master.
```
[ ] Yes
[x] No
```

PCQ-653 Update demo from master

---

src/main/java/uk/gov/hmcts/reform/pcqloader/PcqLoaderComponent.java
src/test/java/uk/gov/hmcts/reform/pcqloader/PcqLoaderComponentTest.java

PCQ-670
If the zip file does not contain metadata.json or file with invalid name then the zip file will be moved to Rejected container.
```
[ ] Yes
[X ] No
```

PCQ670 - Invalid Payload moved to Rejected container.

---

src/integrationTest/java/uk/gov/hmcts/reform/pcqloader/services/BlobStorageManagerTest.java
src/main/java/uk/gov/hmcts/reform/pcqloader/services/BlobStorageManager.java
src/test/java/uk/gov/hmcts/reform/pcqloader/services/BlobStorageManagerTest.java

https://tools.hmcts.net/jira/browse/PCQ-671
Update to only pull blobs from the root of the container
```
[ ] Yes
[x] No
```

PCQ-671: Update to only pull blobs from the root of the container.

---

Jenkinsfile_nightly

PCQ-708
Nightly pipeline update to run all the tests.
```
[ ] Yes
[X ] No
```

Pcq 708 nightly pipeline update

---

build.gradle
security.sh

PCQ708
```
[ ] Yes
[ X] No
```

PCQ708 - Added security.sh and updated build.gradle

---

src/main/java/uk/gov/hmcts/reform/pcqloader/PcqLoaderComponent.java
src/main/java/uk/gov/hmcts/reform/pcqloader/utils/LogSummaryUtils.java
src/test/java/uk/gov/hmcts/reform/pcqloader/PcqLoaderComponentTest.java

PCQ-713
Added improved service logging report.
```
[ ] Yes
[ X] No
```

PCQ713 - Added service logging

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-740
Update to fix vulnerability with older version of httpclient.
```
[ ] Yes
[x] No
```

PCQ-740: Update to fix dependancy vulnerability.

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PCQ-759
Update to upgrade Spring boot and resolve some older suppressions.
```
[ ] Yes
[x] No
```

PCQ-758: Update to upgrade springboot.

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-762
Fix to PCQ-Loader mutation tests following Spring Boot ugrade.
```
[ ] Yes
[x] No
```

PCQ-762-FixToMutationTests

---

Jenkinsfile_nightly
build.gradle

https://tools.hmcts.net/jira/browse/PCQ-766
Enable security check in nightly build.
```
[ ] Yes
[x] No
```

PCQ-766-Enable-Security-Check

---

audit.json

https://tools.hmcts.net/jira/browse/PCQ-766
Add missing audit file for security scan.
```
[ ] Yes
[x] No
```

PCQ-766 Add missing audit file.

---

src/main/java/uk/gov/hmcts/reform/pcqloader/PcqLoaderComponent.java

https://tools.hmcts.net/jira/browse/PCQ-728
Update to logging to test kustomise change.
```
[ ] Yes
[x] No
```

PCQ-728 Update to test kustomise for PCQ Loader.

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-807
Update to use latest netty libraries to remove code vulnerbility.
```
[ ] Yes
[x] No
```

PCQ-807 Updating to use latest netty library.

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-814
Fix to vulnerability in code.
```
[ ] Yes
[x] No
```

PCQ-814: Fix to vulnerability in tomcat.

---

build.gradle
config/checkstyle/checkstyle.xml
config/owasp/suppressions.xml
src/functionalTest/java/uk/gov/hmcts/reform/pcqloader/postdeploy/PcqLoaderTestBase.java
src/integrationTest/java/uk/gov/hmcts/reform/pcqloader/util/PcqBackendIntegrationTest.java
src/main/java/uk/gov/hmcts/reform/pcqloader/PcqLoaderComponent.java
src/main/java/uk/gov/hmcts/reform/pcqloader/helper/PayloadMappingHelper.java
src/main/java/uk/gov/hmcts/reform/pcqloader/services/impl/PcqBackendServiceImpl.java

https://tools.hmcts.net/jira/browse/PCQ-784
Update libraries.
```
[ ] Yes
[x] No
```

Pcq 784 update loader libraries

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-830
Fix vulnerability with netty library.
```
[ ] Yes
[x] No
```

PCQ-830: Fix vulnerability with netty library

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-838
Updated Netty library version to 4.1.61
```
[ ] Yes
[X ] No
```

PCQ-838 - Updated Netty version to 4.1.61

---

charts/pcq-loader/Chart.yaml
charts/pcq-loader/values.yaml

https://tools.hmcts.net/jira/browse/PCQ-840
Helm charts version upgrade.
```
[ ] Yes
[x] No
```

PCQ-840 Updated charts version.

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-843
Update to address CVE in commons-io.
```
[ ] Yes
[x] No
```

PCQ-843: Update to address CVE in Loader

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-869
Fix CVE-2021-22118 in PCQ Java services
```
[ ] Yes
[x] No
```

PCQ-869 Fix CVE-2021-22118 in PCQ Java services

---

security.sh

https://tools.hmcts.net/jira/browse/PCQ-872
Fix ZAP security nightly build script issues
```
[ ] Yes
[x] No
```

Nightly dev

---

Jenkinsfile_nightly
build.gradle
config/fortify-client.properties

https://tools.hmcts.net/jira/browse/PCQ-880
Fortify Integration.
```
[ ] Yes
[x] No
```

PCQ-880: Updated to add fortify pipeline

---

.idea/pcq-loader.iml
build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PCQ-1026
Changed build.gradle to change the version for springFramework and sprinFramework.boot
also added a new version 4.0.1 for Jakarta jar
```
[ ] Yes
[x] No
```

fixed loader vulnerability

---

build.gradle
config/owasp/suppressions.xml
gradle/wrapper/gradle-wrapper.properties
src/functionalTest/java/uk/gov/hmcts/reform/pcqloader/postdeploy/PcqLoaderFunctionalTest.java

https://tools.hmcts.net/jira/browse/PCQ-1026
Spring framework upgrade to 2.5.3
Azure library upgrade 12.13.0
Pcq loader functional test change, deleting the blob before creating one.
```
[ ] Yes
[x] No
```

Pcq1026 spring framework upgrade

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/PCQ-988
This is change is about syncing other branches with master for PCQ-Loader
```
[ ] Yes
[x] No
```

Sync Other Branches with master for Pcq Loader

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1117
This change is to fix dependency check for CVE-2021-22096
```
[ ] Yes
[x] No
```

PCQ-1117 Loader dependency check fixed

---

src/main/java/uk/gov/hmcts/reform/pcqloader/PcqLoaderComponent.java

https://tools.hmcts.net/jira/browse/PCQ-1106
Logging DCN number in log when file is successfully processed
```
[ ] Yes
[x] No
```

PCQ-1106 Logging DCN Number

---

Jenkinsfile_nightly

https://tools.hmcts.net/jira/browse/PCQ-1190
Disable Fortify Scan for Loader
```
[ ] Yes
[x] No
```

PCQ-1190 Diable Loader Fortify Scan

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1195
This change is to upgrade log4j to 2.15.0
```
[ ] Yes
[x] No
```

PCQ-1195 log4j upgrade

---

Jenkinsfile_nightly

https://tools.hmcts.net/jira/browse/PCQ-1212
This change is to Enable Fortify Scan
```
[ ] Yes
[x] No
```

PCQ-1212 Enable Fortify Scan

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1338
This change is to fix dependency check on Loader
```
[ ] Yes
[x] No
```

PCQ-1338 Dependency Check Fix

---

charts/pcq-loader/Chart.yaml

https://tools.hmcts.net/jira/browse/PCQ-1339
This change is to about chart-job update
```
[ ] Yes
[x] No
```

Chart Job update

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1191
This change is for tomcat-embed jar
```
[ ] Yes
[x] No
```

PCQ-1191 Fix jar

---

build.gradle
config/pmd/ruleset.xml
src/functionalTest/java/uk/gov/hmcts/reform/pcqloader/postdeploy/PcqLoaderFunctionalTest.java
src/main/java/uk/gov/hmcts/reform/pcqloader/PcqLoaderComponent.java
src/main/java/uk/gov/hmcts/reform/pcqloader/utils/ZipFileUtils.java
src/test/java/uk/gov/hmcts/reform/pcqloader/PcqLoaderComponentTest.java

https://tools.hmcts.net/jira/browse/PCQ-818
This change is to fix Security Hotspot and bug detected by SonarCloud
```
[ ] Yes
[x] No
```

pcq-818 Security Hotspot and bug fix

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1426
Fix for jackson-databind-2.13.2 dependency check , CVE-2020-36518.
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```

PCQ-1426 Dependency-check-jackson-databind

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PCQ-1452
Update to springframework.boot 2.5.12 and suppress spring-plugin vulnerabilities.
```
[ ] Yes
[x] No
```

PCQ-1452: Suppress vulnerability with spring-plugin.

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1333
This change is to upgrade other libraries
```
[ ] Yes
[x] No
```

PCQ-1333Loader other upgrade

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-87
This change is to fix CVE-2022-29885
```
[ ] Yes
[x] No
```

PCQ-87 Dependency check fixed

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PCQ-876
This change is to fix dependency check 
```
[ ] Yes
[x] No
```

PCQ-876 dependency check fix

---

renovate/configure/renovate.json

https://tools.hmcts.net/jira/browse/PCQ-1335
This change is to configure renovate
```
[ ] Yes
[x] No
```

PCQ-1335 confiuring renovate for Loader

---

Jenkinsfile_CNP
Jenkinsfile_nightly
azure-pipelines-scheduled.yml
azure-pipelines.yml
build.gradle

https://tools.hmcts.net/jira/browse/PCQ-941
Update to fix functional tests being reported as no results.
```
[ ] Yes
[x] No
```

PCQ-941-Fix-Pipeline-Issues

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1529
This change is to fix CVE-2022-25857
```
[ ] Yes
[x] No
```

PCQ-1529 Snakeyaml dependency check fix

---

src/functionalTest/java/uk/gov/hmcts/reform/pcqloader/postdeploy/PcqLoaderFunctionalTest.java

https://tools.hmcts.net/jira/browse/PCQ-1530
This Change is to fix functional test for loader
```
[ ] Yes
[x] No
```

PCQ-1530 remving code for deleting blob container in start

---

src/functionalTest/java/uk/gov/hmcts/reform/pcqloader/postdeploy/PcqLoaderFunctionalTest.java

https://tools.hmcts.net/jira/browse/PCQ-1530
This change is to delay container deletion
```
[ ] Yes
[x] No
```

PCQ-1530 Delay the container deletion

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1535
This change is to fix dependency check related to snakeyml
```
[ ] Yes
[x] No
```

PCQ-1535 depenency check fix

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1537
This change is to fix dependency check 
```
[ ] Yes
[x] No
```

PCQ-1537 dependency check fix

---

Jenkinsfile_nightly

https://tools.hmcts.net/jira/browse/PCQ-1536
This change is to disable Nightly build during weekend
```
[ ] Yes
[x] No
```

PCQ-1536 Disable Nightly build during weekend

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1596
This change is to fix spring-security and tomcat-embed dependency 
```
[ ] Yes
[x] No
```

PCQ-1596 dependency check fix

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1600
This change is to upgrade libraries.
```
[ ] Yes
[x] No
```

PCQ-1600 Upgrading libraries

---

.github/dependabot.yml

https://tools.hmcts.net/jira/browse/PCQ-1617
This change is to reduce dependabot PR weekly 10 to 5 and also ignore any patch version of libraries.
```
[ ] Yes
[x] No
```

PCQ-1617 changing configuration for dependabot

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PCQ-1620
This change is to suppress CVE
```
[ ] Yes
[x] No
```

PCQ-1620 Suppressing CVE

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1618
This change is to upgrade libraries
```
[ ] Yes
[x] No
```

PCQ-1618 dependency upgrade

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1618
This change is to fix Mutation test
```
[ ] Yes
[x] No
```

PCQ-1618 Mutation test fix

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1626
This change is to fix CVE-2022-41881, CVE-2022-41915
```
[ ] Yes
[x] No
```

PCQ-1626 Dependency check fix

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PCQ-1629
This change is suppress CVE
```
[ ] Yes
[x] No
```

PCQ-1629 suppressing CVE

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1631
This change is to suppress CVE-2022-45143
```
[ ] Yes
[x] No
```

PCQ-1631 dependency check

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1639
upgrading wasp dependency check version
```
[ ] Yes
[x] No
```

PCQ-1639 upgrading owasp version

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1640
This change is to fix woodstox dependency
```
[ ] Yes
[x] No
```

PCQ-1640 fixing woodstox dependency

---

charts/pcq-loader/Chart.yaml

https://tools.hmcts.net/jira/browse/PCQ-1622
Upgrade helm release for chart-job
```
[ ] Yes
[x] No
```

PCQ-1622 helm chart-job upgrade

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1622
This change is to fix mutation test
```
[ ] Yes
[x] No
```

PCQ-1622 Mutation test fix

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PCQ-1649
This change is to fix CVE-2022-45688
```
[ ] Yes
[x] No
```

PCQ-1649 suppress CVE-2022-45688

---

.github/dependabot.yml
build.gradle
charts/pcq-loader/Chart.yaml

https://tools.hmcts.net/jira/browse/PCQ-1648
Configuring dependabot to run on Thursday at 6pm
```
[ ] Yes
[x] No
```

PCQ-1648 Configuring dependabot on particular day

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PCQ-1659
This change is to suppress CVE-2022-1471
```
[ ] Yes
[x] No
```

PCQ-1659 suppress CVE-2022-1471

---

build.gradle

This change is to fix CVE-2023-20861 for spring framework
```
[ ] Yes
[x] No
```

Spring-framework CVE-2023-20861 Fix

---

build.gradle
src/main/java/uk/gov/hmcts/reform/pcqloader/helper/PayloadMappingHelper.java
src/main/java/uk/gov/hmcts/reform/pcqloader/services/BlobStorageManager.java
src/test/java/uk/gov/hmcts/reform/pcqloader/helper/PayloadMappingHelperTest.java

https://tools.hmcts.net/jira/browse/PCQ-1645
This change is to upgrade springBoot and other libraries
```
[ ] Yes
[x] No
```

PCQ-1645 spring boot upgrade

---

src/main/java/uk/gov/hmcts/reform/pcqloader/utils/AppInsightsConfig.java

Create telemetryclient bean
Create telemetryclient bean
```
[ ] Yes
[x] No
```

Create telemetryclient bean

---

src/test/java/uk/gov/hmcts/reform/pcqloader/utils/AppInsightsConfigTest.java

**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```

Add tests.

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PCQ-1645
Fixing appInsights and suppressing CVE
```
[ ] Yes
[x] No
```

PCQ-1645 Fixing appInsights and suppressing CVE

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1645
Add appinsights lib
```
[ ] Yes
[x] No
```

Add appinsights lib

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1718
This change is to upgrade SpringBoot upgrade
```
[ ] Yes
[x] No
```

PCQ-1718 upgrade spring bootFramework

---

src/main/java/uk/gov/hmcts/reform/pcqloader/PcqLoaderComponent.java
src/main/java/uk/gov/hmcts/reform/pcqloader/helper/PayloadMappingHelper.java
src/main/java/uk/gov/hmcts/reform/pcqloader/services/BlobStorageManager.java

https://tools.hmcts.net/jira/browse/PCQ-1608
Remove unnecessary logs.
```
[ ] Yes
[x] No
```

Remove unnecessary logs.

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1656
Upgrading snakeyml version to 2.0
```
[ ] Yes
[x] No
```

PCQ-1656 upgrade snakeyml version to 2.0

---

charts/pcq-loader/Chart.yaml
charts/pcq-loader/values.yaml

https://tools.hmcts.net/jira/browse/PCQ-1730
remove unneccessary keys
```
[ ] Yes
[x] No
```

PCQ-1730 key store config

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PCQ-1757
This change into suppress CVE-2023-35116
```
[ ] Yes
[x] No
```

PCQ-1757 Suppress CVE-2023-35116

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1783
This change is to fix dependency check
```
[ ] Yes
[x] No
```

PCQ-1783 dependency check fix

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1807
This change is to fix CVE-2023-41080
```
[ ] Yes
[x] No
```

PCQ-1807 tomcat upgrade for CVE-2023-41080

---

Jenkinsfile_CNP

Remove enableCleanupOfHelmReleaseOnSuccess
```
[ ] Yes
[x] No
```

Remove enableCleanupOfHelmReleaseOnSuccess

---

lib/applicationinsights.json

https://tools.hmcts.net/jira/browse/PCQ-1750
Log 1% of health message
```
[ ] Yes
[x] No
```

PCQ-1750 log 1% of health message in application insight

---

build.gradle

logback dependency fix
```
[ ] Yes
[x] No
```

fix dependency for logback

---

charts/pcq-loader/Chart.yaml
charts/pcq-loader/values.yaml

https://tools.hmcts.net/jira/browse/PCQ-1854
This change is to enable disableActiveClusterCheck to true
```
[ ] Yes
[x] No
```

PCQ-1854 dosableActiveClusterCheck to true

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PCQ-1856
This change is to extend time on CVE-2023-36052
```
[ ] Yes
[x] No
```

PCQ-1856 extend time for cve-2023-36052

---

charts/pcq-loader/Chart.yaml
charts/pcq-loader/values.yaml

https://tools.hmcts.net/jira/browse/PCQ-1859
This change is to upgrade pcq-loader charts-job version
```
[ ] Yes
[x] No
```

PCQ-1859 charts-job upgrade

---

build.gradle
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/pcqloader/services/BlobStorageManager.java
src/test/java/uk/gov/hmcts/reform/pcqloader/services/BlobStorageManagerTest.java

https://tools.hmcts.net/jira/browse/PCQ-1728
azure-storage-blob upgrade
```
[ ] Yes
[x] No
```

PCQ-1728 azure-storage-blob upgrade

---

build.gradle

Bump pitest junit plugin version to fix failing mutation tests

Bump pitest junit plugin version

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/pcqloader/postdeploy/PcqLoaderMappingFunctionalTest.java
src/functionalTest/resources/application-functional.yaml
src/main/java/uk/gov/hmcts/reform/pcqloader/PcqLoaderApplication.java
src/main/java/uk/gov/hmcts/reform/pcqloader/PcqLoaderComponent.java
src/main/java/uk/gov/hmcts/reform/pcqloader/exceptions/BlobProcessingException.java
src/main/java/uk/gov/hmcts/reform/pcqloader/exceptions/ZipProcessingException.java
src/main/java/uk/gov/hmcts/reform/pcqloader/helper/PayloadMappingHelper.java
src/main/java/uk/gov/hmcts/reform/pcqloader/helper/PayloadMappingHelperBase.java
src/main/java/uk/gov/hmcts/reform/pcqloader/services/impl/PcqBackendServiceImpl.java
src/main/resources/application.yaml
src/test/resources/application.yaml

https://tools.hmcts.net/jira/browse/PCQ-1651
Address sonar lint code smells

PCQ-1651 address code smells

---

config/owasp/suppressions.xml

Suppress azure cve until fix
```
[ ] Yes
[x] No
```

suppress azure cve

---

Dockerfile
build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1971
Upgrade to Java 21
```
[ ] Yes
[x] No
```

PCQ-1971 upgrade to Java 21

---

config/owasp/suppressions.xml

Remove unnecessary suppression
```
[ ] Yes
[x] No
```

Remove unneccessary suppression

---

.github/CODEOWNERS

https://tools.hmcts.net/jira/browse/PCQ-1978
```
[ ] Yes
[x] No
```

PCQ-1978 add CODEOWNERS

---

Dockerfile

https://tools.hmcts.net/jira/browse/PCQ-1984
Change to non root user
```
[ ] Yes
[x] No
```

PCQ-1984 change to non-root  hmcts user

---

build.gradle

https://tools.hmcts.net/jira/browse/CME-518
Replace jitpack with azure artifactory
```
[ ] Yes
[x] No
```

CME-518 replace jitpack with azure artifactory

---

src/functionalTest/resources/application-functional.yaml
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/PCQ-2029
This change is remove this random key from git hub to avoid any confusion of secret exposed
```
[ ] Yes
[x] No
```

PCQ-2029 remove random key to connect to stage account
